ley = 0.0

[db]
  databaseconfigpath = ""
  databasename = ""
  hosts = []
  password = ""
  user = ""

[log]
  invalidfieldslog = "avada"
  missingdocsimportedlog = ""

[run]
  consumergoroutines = 0.0
  readergoroutines = 0.0
  [run.mode]
    mom = 0.0
    [run.mode.dad]
      minus = "pan"
      plus = ""
