debug_mode = false
encryption_key = ""

[cache]
  db_urls = ["ss", "sd"]
  expiration_min = 0

[server]
  max_percent_cpu_usage = 0
  port = 0
  request_timeout_seconds = 0

[tracer]
  endpoint_url = ""
  service_name = ""
  url_path = ""
