
[database]
  dbConfig = "a"
  dbName = "b"
  hosts = ["c", "d"]
  password = ""
  user = ""

[log]
  invalidFieldsLog = "lo"
  missingDocsImportedLog = ""

[run]
  consumerGoroutines = 0
  mode = 2
  readerGoroutines = 0
