
[database]
  dbConfig = "eriireir"
  dbName = ""
  hosts = []
  password = ""
  user = ""

[log]
  invalidFieldsLog = ""
  missingDocsImportedLog = ""

[run]
  consumerGoroutines = 57
  mode = 8
  readerGoroutines = 2
