
[database]
  dbConfig = ""
  dbName = ""
  hosts = []
  password = ""
  user = ""

[log]
  invalidFieldsLog = ""
  missingDocsImportedLog = ""

[run]
  consumerGoroutines = 0
  mode = 0
  readerGoroutines = 0
