
[database]
  dbConfig = "jrj"
  dbName = ""
  hosts = []
  password = ""
  user = ""

[log]
  invalidFieldsLog = ""
  missingDocsImportedLog = ""

[run]
  consumerGoroutines = 1
  mode = 2
  readerGoroutines = 3
